version: "3"
services:
  garage:
    image: dxflrs/garage:v2.3.0
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /volume1/docker/garage/garage.toml:/etc/garage.toml
      - /volume1/docker/garage/meta:/var/lib/garage/meta
      - /volume1/docker/garage/data:/var/lib/garage/data